# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: textminingservice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import request_pb2 as request__pb2
from . import topicmining_pb2 as topicmining__pb2
from . import textsummary_pb2 as textsummary__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='textminingservice.proto',
  package='grpc_protos.textmining',
  syntax='proto3',
  serialized_options=_b('\n\017grpc.textminingB\021TextMiningServiceP\000'),
  serialized_pb=_b('\n\x17textminingservice.proto\x12\x16grpc_protos.textmining\x1a\rrequest.proto\x1a\x11topicmining.proto\x1a\x11textsummary.proto2\xc4\x01\n\nTextMining\x12W\n\x0eGenerateTopics\x12\x1f.grpc_protos.textmining.Request\x1a\x1e.grpc_protos.textmining.Topics\"\x00(\x01\x30\x01\x12]\n\x13GenerateTextSummary\x12\x1f.grpc_protos.textmining.Request\x1a\x1f.grpc_protos.textmining.Summary\"\x00(\x01\x30\x01\x42&\n\x0fgrpc.textminingB\x11TextMiningServiceP\x00\x62\x06proto3')
  ,
  dependencies=[request__pb2.DESCRIPTOR,topicmining__pb2.DESCRIPTOR,textsummary__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_TEXTMINING = _descriptor.ServiceDescriptor(
  name='TextMining',
  full_name='grpc_protos.textmining.TextMining',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=105,
  serialized_end=301,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenerateTopics',
    full_name='grpc_protos.textmining.TextMining.GenerateTopics',
    index=0,
    containing_service=None,
    input_type=request__pb2._REQUEST,
    output_type=topicmining__pb2._TOPICS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GenerateTextSummary',
    full_name='grpc_protos.textmining.TextMining.GenerateTextSummary',
    index=1,
    containing_service=None,
    input_type=request__pb2._REQUEST,
    output_type=textsummary__pb2._SUMMARY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEXTMINING)

DESCRIPTOR.services_by_name['TextMining'] = _TEXTMINING

# @@protoc_insertion_point(module_scope)
