# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: textsummary.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='textsummary.proto',
  package='grpc_protos.textmining',
  syntax='proto3',
  serialized_options=_b('\n\"grpc_protos.textmining.textsummaryB\013TextSummaryP\000'),
  serialized_pb=_b('\n\x11textsummary.proto\x12\x16grpc_protos.textmining\"\x1a\n\x07Summary\x12\x0f\n\x07summary\x18\x01 \x01(\tB3\n\"grpc_protos.textmining.textsummaryB\x0bTextSummaryP\x00\x62\x06proto3')
)




_SUMMARY = _descriptor.Descriptor(
  name='Summary',
  full_name='grpc_protos.textmining.Summary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='summary', full_name='grpc_protos.textmining.Summary.summary', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['Summary'] = _SUMMARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Summary = _reflection.GeneratedProtocolMessageType('Summary', (_message.Message,), dict(
  DESCRIPTOR = _SUMMARY,
  __module__ = 'textsummary_pb2'
  # @@protoc_insertion_point(class_scope:grpc_protos.textmining.Summary)
  ))
_sym_db.RegisterMessage(Summary)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
