# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicmining.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='topicmining.proto',
  package='grpc_protos.textmining',
  syntax='proto3',
  serialized_options=_b('\n\"grpc_protos.textmining.topicminingB\006TopicsP\000'),
  serialized_pb=_b('\n\x11topicmining.proto\x12\x16grpc_protos.textmining\"C\n\x06Topics\x12\x39\n\x06topics\x18\x01 \x03(\x0b\x32).grpc_protos.textmining.TopicDistribution\"h\n\x11TopicDistribution\x12\x41\n\x10word_probability\x18\x01 \x03(\x0b\x32\'.grpc_protos.textmining.WordProbability\x12\x10\n\x08\x63overage\x18\x02 \x01(\x01\"4\n\x0fWordProbability\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x13\n\x0bprobability\x18\x02 \x01(\x01\x42.\n\"grpc_protos.textmining.topicminingB\x06TopicsP\x00\x62\x06proto3')
)




_TOPICS = _descriptor.Descriptor(
  name='Topics',
  full_name='grpc_protos.textmining.Topics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topics', full_name='grpc_protos.textmining.Topics.topics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=112,
)


_TOPICDISTRIBUTION = _descriptor.Descriptor(
  name='TopicDistribution',
  full_name='grpc_protos.textmining.TopicDistribution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word_probability', full_name='grpc_protos.textmining.TopicDistribution.word_probability', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coverage', full_name='grpc_protos.textmining.TopicDistribution.coverage', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=218,
)


_WORDPROBABILITY = _descriptor.Descriptor(
  name='WordProbability',
  full_name='grpc_protos.textmining.WordProbability',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='grpc_protos.textmining.WordProbability.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='probability', full_name='grpc_protos.textmining.WordProbability.probability', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=272,
)

_TOPICS.fields_by_name['topics'].message_type = _TOPICDISTRIBUTION
_TOPICDISTRIBUTION.fields_by_name['word_probability'].message_type = _WORDPROBABILITY
DESCRIPTOR.message_types_by_name['Topics'] = _TOPICS
DESCRIPTOR.message_types_by_name['TopicDistribution'] = _TOPICDISTRIBUTION
DESCRIPTOR.message_types_by_name['WordProbability'] = _WORDPROBABILITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Topics = _reflection.GeneratedProtocolMessageType('Topics', (_message.Message,), dict(
  DESCRIPTOR = _TOPICS,
  __module__ = 'topicmining_pb2'
  # @@protoc_insertion_point(class_scope:grpc_protos.textmining.Topics)
  ))
_sym_db.RegisterMessage(Topics)

TopicDistribution = _reflection.GeneratedProtocolMessageType('TopicDistribution', (_message.Message,), dict(
  DESCRIPTOR = _TOPICDISTRIBUTION,
  __module__ = 'topicmining_pb2'
  # @@protoc_insertion_point(class_scope:grpc_protos.textmining.TopicDistribution)
  ))
_sym_db.RegisterMessage(TopicDistribution)

WordProbability = _reflection.GeneratedProtocolMessageType('WordProbability', (_message.Message,), dict(
  DESCRIPTOR = _WORDPROBABILITY,
  __module__ = 'topicmining_pb2'
  # @@protoc_insertion_point(class_scope:grpc_protos.textmining.WordProbability)
  ))
_sym_db.RegisterMessage(WordProbability)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
