# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import topicgeneration_pb2 as topicgeneration__pb2


class TopicGenerationStub(object):
  """The Generation service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GenerateTopicsDirect = channel.unary_unary(
        '/grpc.document.TopicGeneration/GenerateTopicsDirect',
        request_serializer=topicgeneration__pb2.FileLocation.SerializeToString,
        response_deserializer=topicgeneration__pb2.Topics.FromString,
        )
    self.GenerateTopicsIndirect = channel.unary_unary(
        '/grpc.document.TopicGeneration/GenerateTopicsIndirect',
        request_serializer=topicgeneration__pb2.FileLocation.SerializeToString,
        response_deserializer=topicgeneration__pb2.FileLocation.FromString,
        )


class TopicGenerationServicer(object):
  """The Generation service definition.
  """

  def GenerateTopicsDirect(self, request, context):
    """Sends a request to get topics from a file
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GenerateTopicsIndirect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TopicGenerationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GenerateTopicsDirect': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateTopicsDirect,
          request_deserializer=topicgeneration__pb2.FileLocation.FromString,
          response_serializer=topicgeneration__pb2.Topics.SerializeToString,
      ),
      'GenerateTopicsIndirect': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateTopicsIndirect,
          request_deserializer=topicgeneration__pb2.FileLocation.FromString,
          response_serializer=topicgeneration__pb2.FileLocation.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc.document.TopicGeneration', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
