# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topicgeneration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='topicgeneration.proto',
  package='grpc.document',
  syntax='proto3',
  serialized_options=_b('\n\rgrpc.documentB\nGenerationP\000'),
  serialized_pb=_b('\n\x15topicgeneration.proto\x12\rgrpc.document\" \n\x0c\x46ileLocation\x12\x10\n\x08location\x18\x01 \x01(\t\"\x18\n\x06Topics\x12\x0e\n\x06topics\x18\x01 \x03(\t2\xb5\x01\n\x0fTopicGeneration\x12L\n\x14GenerateTopicsDirect\x12\x1b.grpc.document.FileLocation\x1a\x15.grpc.document.Topics\"\x00\x12T\n\x16GenerateTopicsIndirect\x12\x1b.grpc.document.FileLocation\x1a\x1b.grpc.document.FileLocation\"\x00\x42\x1d\n\rgrpc.documentB\nGenerationP\x00\x62\x06proto3')
)




_FILELOCATION = _descriptor.Descriptor(
  name='FileLocation',
  full_name='grpc.document.FileLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='grpc.document.FileLocation.location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=72,
)


_TOPICS = _descriptor.Descriptor(
  name='Topics',
  full_name='grpc.document.Topics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topics', full_name='grpc.document.Topics.topics', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['FileLocation'] = _FILELOCATION
DESCRIPTOR.message_types_by_name['Topics'] = _TOPICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileLocation = _reflection.GeneratedProtocolMessageType('FileLocation', (_message.Message,), dict(
  DESCRIPTOR = _FILELOCATION,
  __module__ = 'topicgeneration_pb2'
  # @@protoc_insertion_point(class_scope:grpc.document.FileLocation)
  ))
_sym_db.RegisterMessage(FileLocation)

Topics = _reflection.GeneratedProtocolMessageType('Topics', (_message.Message,), dict(
  DESCRIPTOR = _TOPICS,
  __module__ = 'topicgeneration_pb2'
  # @@protoc_insertion_point(class_scope:grpc.document.Topics)
  ))
_sym_db.RegisterMessage(Topics)


DESCRIPTOR._options = None

_TOPICGENERATION = _descriptor.ServiceDescriptor(
  name='TopicGeneration',
  full_name='grpc.document.TopicGeneration',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=101,
  serialized_end=282,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenerateTopicsDirect',
    full_name='grpc.document.TopicGeneration.GenerateTopicsDirect',
    index=0,
    containing_service=None,
    input_type=_FILELOCATION,
    output_type=_TOPICS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GenerateTopicsIndirect',
    full_name='grpc.document.TopicGeneration.GenerateTopicsIndirect',
    index=1,
    containing_service=None,
    input_type=_FILELOCATION,
    output_type=_FILELOCATION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TOPICGENERATION)

DESCRIPTOR.services_by_name['TopicGeneration'] = _TOPICGENERATION

# @@protoc_insertion_point(module_scope)
